image:
  name: "giantswarm/app-exporter"
  tag: "[[ .Version ]]"

registry:
  domain: docker.io

provider:
  kind: aws

pod:
  user:
    id: 1000
  group:
    id: 1000
project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"
